import { useState } from "react";
import { Download } from "lucide-react";
import { showToast } from "@/components/ui/toast";
import type { NewsArticle, MarketData, SentimentDistribution, ImpactAnalysis, Alert } from "@/lib/api";
import type { jsPDF } from "jspdf";

interface PdfExportProps {
  news: NewsArticle[];
  marketData: MarketData[];
  sentimentData: SentimentDistribution[];
  impacts: ImpactAnalysis[];
  alerts: Alert[];
}

const C = {
  primary: [6, 6, 12] as [number, number, number],
  accent: [0, 188, 212] as [number, number, number],
  cyan: [0, 188, 212] as [number, number, number],
  purple: [147, 51, 234] as [number, number, number],
  green: [16, 185, 129] as [number, number, number],
  red: [239, 68, 68] as [number, number, number],
  amber: [245, 158, 11] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  lightGray: [248, 250, 252] as [number, number, number],
  midGray: [148, 163, 184] as [number, number, number],
  darkGray: [30, 41, 59] as [number, number, number],
  tableHeader: [15, 23, 42] as [number, number, number],
};

function drawHeader(doc: jsPDF, pw: number) {
  doc.setFillColor(...C.primary);
  doc.rect(0, 0, pw, 40, "F");
  doc.setFillColor(...C.accent);
  doc.rect(0, 38, pw, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...C.white);
  doc.text("NEURAL ENGINE", 20, 17);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(120, 160, 180);
  doc.text("AI-POWERED FINANCIAL INTELLIGENCE", 20, 25);
  doc.setFontSize(7);
  doc.setTextColor(100, 140, 160);
  doc.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" }), pw - 20, 17, { align: "right" });
}

function drawFooter(doc: jsPDF, pw: number, ph: number, page: number) {
  doc.setFillColor(...C.primary);
  doc.rect(0, ph - 16, pw, 16, "F");
  doc.setFillColor(...C.accent);
  doc.rect(0, ph - 16, pw, 0.5, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(100, 140, 160);
  doc.text("Neural Engine AI  |  Confidential  |  Generated by AI-Powered Analytics", 20, ph - 8);
  doc.text(`Page ${page}`, pw - 20, ph - 8, { align: "right" });
}

function sectionTitle(doc: jsPDF, title: string, y: number, pw: number) {
  doc.setFillColor(...C.lightGray);
  doc.roundedRect(15, y - 5, pw - 30, 12, 2, 2, "F");
  doc.setFillColor(...C.accent);
  doc.rect(15, y - 5, 3, 12, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...C.darkGray);
  doc.text(title, 22, y + 3);
  return y + 14;
}

function kpiCard(doc: jsPDF, x: number, y: number, w: number, h: number, label: string, value: string, color: [number, number, number]) {
  doc.setFillColor(250, 251, 252);
  doc.roundedRect(x, y, w, h, 3, 3, "F");
  doc.setFillColor(...color);
  doc.roundedRect(x, y, w, 2.5, 3, 3, "F");
  doc.rect(x, y + 1, w, 1.5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...color);
  doc.text(value, x + w / 2, y + h / 2 + 2, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(...C.midGray);
  doc.text(label.toUpperCase(), x + w / 2, y + h / 2 + 9, { align: "center" });
}

function sentimentBar(doc: jsPDF, x: number, y: number, w: number, label: string, count: number, total: number, color: [number, number, number]) {
  const pct = total > 0 ? count / total : 0;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...C.darkGray);
  doc.text(label, x, y + 6);
  const bx = x + 50;
  const bw = w - 80;
  doc.setFillColor(240, 240, 240);
  doc.roundedRect(bx, y + 1, bw, 5, 2, 2, "F");
  if (pct > 0) {
    doc.setFillColor(...color);
    doc.roundedRect(bx, y + 1, Math.max(bw * pct, 4), 5, 2, 2, "F");
  }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...C.darkGray);
  doc.text(`${count} (${(pct * 100).toFixed(0)}%)`, bx + bw + 3, y + 6);
}

export function PdfExport({ news, marketData, sentimentData, impacts, alerts }: PdfExportProps) {
  const [generating, setGenerating] = useState(false);

  const generate = async () => {
    setGenerating(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF("p", "mm", "a4");
      const pw = doc.internal.pageSize.getWidth();
      const ph = doc.internal.pageSize.getHeight();
      const m = 20;
      const cw = pw - m * 2;
      let pageNum = 1;
      let y = 0;

      const finishPage = () => { drawFooter(doc, pw, ph, pageNum); doc.addPage(); pageNum++; y = 50; };
      const checkPage = (n: number) => { if (y + n > ph - 30) finishPage(); };

      // === COVER PAGE ===
      doc.setFillColor(...C.primary);
      doc.rect(0, 0, pw, ph, "F");
      doc.setFillColor(...C.accent);
      doc.rect(0, 70, pw, 3, "F");

      doc.setFillColor(0, 188, 212);
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (doc as any).setGState(new (doc as any).GState({ opacity: 0.08 }));
      doc.circle(pw - 40, 40, 60, "F");
      doc.circle(30, ph - 50, 45, "F");
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (doc as any).setGState(new (doc as any).GState({ opacity: 1 }));

      doc.setFont("helvetica", "bold");
      doc.setFontSize(32);
      doc.setTextColor(...C.white);
      doc.text("NEURAL ENGINE", pw / 2, 100, { align: "center" });
      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);
      doc.setTextColor(0, 188, 212);
      doc.text("AI-POWERED FINANCIAL INTELLIGENCE", pw / 2, 112, { align: "center" });
      doc.setFillColor(...C.accent);
      doc.roundedRect(pw / 2 - 25, 120, 50, 1, 1, 1, "F");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(...C.white);
      doc.text("MARKET ANALYSIS REPORT", pw / 2, 140, { align: "center" });
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(150, 180, 200);
      doc.text(new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" }), pw / 2, 155, { align: "center" });

      const coverKPIs = [
        { label: "Articles", value: String(news.length), color: C.cyan },
        { label: "Markets", value: String(marketData.length), color: C.purple },
        { label: "Signals", value: String(impacts.length), color: C.green },
        { label: "Alerts", value: String(alerts.length), color: C.amber },
      ];
      const kbW = 35, kbH = 28;
      const kStart = (pw - coverKPIs.length * (kbW + 8) + 8) / 2;
      coverKPIs.forEach((k, i) => {
        const kx = kStart + i * (kbW + 8);
        doc.setFillColor(255, 255, 255);
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (doc as any).setGState(new (doc as any).GState({ opacity: 0.06 }));
        doc.roundedRect(kx, 185, kbW, kbH, 4, 4, "F");
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (doc as any).setGState(new (doc as any).GState({ opacity: 1 }));
        doc.setFillColor(...k.color);
        doc.roundedRect(kx, 185, kbW, 2, 4, 4, "F");
        doc.rect(kx, 186, kbW, 1, "F");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(18);
        doc.setTextColor(...C.white);
        doc.text(k.value, kx + kbW / 2, 200, { align: "center" });
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7);
        doc.setTextColor(120, 160, 180);
        doc.text(k.label.toUpperCase(), kx + kbW / 2, 208, { align: "center" });
      });

      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(80, 100, 120);
      doc.text("This report is generated by AI-powered analysis. Not financial advice.", pw / 2, 240, { align: "center" });
      doc.text("Data sourced from Finnhub, NewsAPI, CoinGecko, and Binance.", pw / 2, 245, { align: "center" });

      drawFooter(doc, pw, ph, pageNum);
      doc.addPage();
      pageNum++;
      y = 50;

      // === PAGE 2: EXECUTIVE SUMMARY ===
      drawHeader(doc, pw);
      y = 50;
      y = sectionTitle(doc, "EXECUTIVE SUMMARY", y, pw);
      y += 2;

      const totalS = sentimentData.reduce((s, d) => s + d.count, 0);
      const bullish = sentimentData.find((s) => s.sentiment === "bullish")?.count || 0;
      const bearish = sentimentData.find((s) => s.sentiment === "bearish")?.count || 0;
      const bullishPct = totalS > 0 ? ((bullish / totalS) * 100).toFixed(0) : "0";
      const highImpact = impacts.filter((i) => i.risk_level === "high").length;
      const topMovers = marketData.filter((m) => m.change_pct !== 0).sort((a, b) => Math.abs(b.change_pct) - Math.abs(a.change_pct)).slice(0, 3);

      const kpis = [
        { label: "News Articles", value: String(news.length), color: C.cyan },
        { label: "Market Assets", value: String(marketData.length), color: C.purple },
        { label: "Bullish Ratio", value: `${bullishPct}%`, color: C.green },
        { label: "High Impact", value: String(highImpact), color: C.red },
      ];
      const kpiW = (cw - 3 * 6) / 4;
      kpis.forEach((k, i) => kpiCard(doc, m + i * (kpiW + 6), y, kpiW, 26, k.label, k.value, k.color));
      y += 36;

      const mood = bullish > bearish ? "BULLISH" : bearish > bullish ? "BEARISH" : "NEUTRAL";
      const moodColor = bullish > bearish ? C.green : bearish > bullish ? C.red : C.amber;
      doc.setFillColor(...C.lightGray);
      doc.roundedRect(m, y, cw, 14, 3, 3, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(...C.darkGray);
      doc.text("Overall Market Mood:", m + 5, y + 9);
      doc.setTextColor(...moodColor);
      doc.text(mood, m + 50, y + 9);
      if (topMovers.length > 0) {
        doc.setTextColor(...C.midGray);
        doc.text(topMovers.map((t) => `${t.symbol} (${t.change_pct > 0 ? "+" : ""}${t.change_pct.toFixed(2)}%)`).join("  |  "), m + 70, y + 9);
      }
      y += 22;

      // Sentiment
      y = sectionTitle(doc, "SENTIMENT ANALYSIS", y, pw);
      y += 4;
      if (totalS > 0) {
        sentimentBar(doc, m, y, cw, "Bullish", bullish, totalS, C.green); y += 14;
        sentimentBar(doc, m, y, cw, "Bearish", bearish, totalS, C.red); y += 14;
        const neutral = sentimentData.find((s) => s.sentiment === "neutral")?.count || 0;
        sentimentBar(doc, m, y, cw, "Neutral", neutral, totalS, C.amber); y += 20;
      } else {
        doc.setFont("helvetica", "italic");
        doc.setFontSize(9);
        doc.setTextColor(...C.midGray);
        doc.text("No sentiment data available yet.", m + 5, y + 5);
        y += 14;
      }

      // Top movers table
      y = sectionTitle(doc, "TOP MOVERS", y, pw);
      y += 2;
      if (marketData.length > 0) {
        doc.setFillColor(...C.tableHeader);
        doc.roundedRect(m, y, cw, 8, 2, 2, "F");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7);
        doc.setTextColor(...C.white);
        doc.text("SYMBOL", m + 4, y + 5.5);
        doc.text("TYPE", m + 40, y + 5.5);
        doc.text("PRICE", m + 80, y + 5.5);
        doc.text("24H CHANGE", m + 120, y + 5.5);
        doc.text("TREND", m + 160, y + 5.5);
        y += 10;

        [...marketData].sort((a, b) => Math.abs(b.change_pct) - Math.abs(a.change_pct)).slice(0, 12).forEach((mkt, idx) => {
          if (idx % 2 === 0) { doc.setFillColor(250, 251, 252); doc.rect(m, y - 1, cw, 7, "F"); }
          doc.setFont("helvetica", "bold");
          doc.setFontSize(7);
          doc.setTextColor(...C.darkGray);
          doc.text(mkt.symbol, m + 4, y + 4);
          doc.setFont("helvetica", "normal");
          doc.setTextColor(...C.midGray);
          doc.text(mkt.asset_type.toUpperCase(), m + 40, y + 4);
          doc.setTextColor(...C.darkGray);
          doc.text(`$${mkt.price.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, m + 80, y + 4);
          const cc = mkt.change_pct > 0 ? C.green : mkt.change_pct < 0 ? C.red : C.midGray;
          doc.setTextColor(...cc);
          doc.text(`${mkt.change_pct > 0 ? "+" : ""}${mkt.change_pct.toFixed(2)}%`, m + 120, y + 4);
          const trend = mkt.change_pct > 1 ? "Strong Up" : mkt.change_pct > 0 ? "Up" : mkt.change_pct < -1 ? "Strong Down" : mkt.change_pct < 0 ? "Down" : "Flat";
          doc.text(trend, m + 160, y + 4);
          y += 7;
        });
        y += 6;
      }

      // === PAGE 3: NEWS ===
      finishPage();
      drawHeader(doc, pw);
      y = sectionTitle(doc, "TOP NEWS HEADLINES", y, pw);
      y += 2;

      news.slice(0, 10).forEach((article) => {
        checkPage(20);
        const sl = article.sentiment?.sentiment || "neutral";
        const sc = sl === "bullish" ? C.green : sl === "bearish" ? C.red : C.amber;

        doc.setFillColor(250, 251, 252);
        doc.roundedRect(m, y, cw, 18, 2, 2, "F");
        doc.setFillColor(...sc);
        doc.roundedRect(m, y, 2.5, 18, 2, 2, "F");
        doc.rect(m, y + 2, 2.5, 14, "F");

        doc.setFont("helvetica", "bold");
        doc.setFontSize(8);
        doc.setTextColor(...C.darkGray);
        const tl = doc.splitTextToSize(article.title, cw - 10);
        doc.text(tl[0], m + 6, y + 6);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(6.5);
        doc.setTextColor(...C.midGray);
        const src = article.source_name || article.source;
        const dt = new Date(article.published_at).toLocaleDateString("en-US", { month: "short", day: "numeric" });
        const tick = article.tickers?.length ? `  |  ${article.tickers.slice(0, 3).join(", ")}` : "";
        doc.text(`${src}  |  ${dt}${tick}`, m + 6, y + 11);

        doc.setFillColor(...sc);
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (doc as any).setGState(new (doc as any).GState({ opacity: 0.12 }));
        doc.roundedRect(m + cw - 30, y + 3, 26, 7, 2, 2, "F");
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (doc as any).setGState(new (doc as any).GState({ opacity: 1 }));
        doc.setFont("helvetica", "bold");
        doc.setFontSize(6);
        doc.setTextColor(...sc);
        doc.text(sl.toUpperCase(), m + cw - 17, y + 7.5, { align: "center" });
        y += 20;
      });
      y += 4;

      // === IMPACTS ===
      if (impacts.length > 0) {
        checkPage(30);
        y = sectionTitle(doc, "IMPACT ANALYSIS", y, pw);
        y += 2;

        impacts.slice(0, 8).forEach((impact) => {
          checkPage(22);
          const rc = impact.risk_level === "high" ? C.red : impact.risk_level === "medium" ? C.amber : C.green;

          doc.setFillColor(250, 251, 252);
          doc.roundedRect(m, y, cw, 20, 2, 2, "F");
          doc.setFillColor(...rc);
          doc.roundedRect(m, y, 2.5, 20, 2, 2, "F");
          doc.rect(m, y + 2, 2.5, 16, "F");

          doc.setFont("helvetica", "bold");
          doc.setFontSize(7.5);
          doc.setTextColor(...C.darkGray);
          const it = doc.splitTextToSize(impact.news_title || "Impact Event", cw - 40);
          doc.text(it[0], m + 6, y + 6);

          doc.setFillColor(...rc);
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (doc as any).setGState(new (doc as any).GState({ opacity: 0.12 }));
          doc.roundedRect(m + cw - 28, y + 2, 24, 7, 2, 2, "F");
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (doc as any).setGState(new (doc as any).GState({ opacity: 1 }));
          doc.setFont("helvetica", "bold");
          doc.setFontSize(6);
          doc.setTextColor(...rc);
          doc.text(impact.risk_level.toUpperCase(), m + cw - 16, y + 6.5, { align: "center" });

          const assets = impact.affected_assets || [];
          if (assets.length > 0) {
            doc.setFont("helvetica", "normal");
            doc.setFontSize(6.5);
            doc.setTextColor(...C.midGray);
            doc.text(`Affected: ${assets.slice(0, 5).map((a) => `${a.symbol} (${a.direction})`).join("  ")}`, m + 6, y + 12);
          }
          if (impact.reasoning) {
            doc.setFont("helvetica", "italic");
            doc.setFontSize(6.5);
            doc.setTextColor(100, 116, 139);
            const rl = doc.splitTextToSize(impact.reasoning, cw - 12);
            doc.text(rl[0].slice(0, 120) + (rl[0].length > 120 ? "..." : ""), m + 6, y + 17);
          }
          y += 22;
        });
      }

      // === PAGE 4: ALERTS + METHODOLOGY ===
      finishPage();
      drawHeader(doc, pw);

      if (alerts.length > 0) {
        y = sectionTitle(doc, "ALERT HISTORY", y, pw);
        y += 2;
        alerts.slice(0, 10).forEach((alert) => {
          checkPage(14);
          doc.setFillColor(250, 251, 252);
          doc.roundedRect(m, y, cw, 10, 2, 2, "F");
          doc.setFont("helvetica", "bold");
          doc.setFontSize(7);
          doc.setTextColor(...C.darkGray);
          doc.text(alert.title || "Alert", m + 5, y + 4.5);
          doc.setFont("helvetica", "normal");
          doc.setFontSize(6.5);
          doc.setTextColor(...C.midGray);
          doc.text(`${alert.channel || "system"}  |  ${alert.timestamp ? new Date(alert.timestamp).toLocaleString() : ""}`, m + 5, y + 8);
          y += 12;
        });
        y += 6;
      }

      // Methodology
      y = sectionTitle(doc, "METHODOLOGY & DATA SOURCES", y, pw);
      y += 4;
      const methodLines: Array<{ text: string; bold?: boolean }> = [
        { text: "This report is generated using AI-powered financial analysis combining real-time market data with natural language processing." },
        { text: "" },
        { text: "Data Sources:", bold: true },
        { text: "  Finnhub: Real-time stock quotes, company news, and market sentiment" },
        { text: "  NewsAPI: Financial news headlines and article content" },
        { text: "  CoinGecko: Cryptocurrency prices, market cap, and trends" },
        { text: "  Binance: Crypto trading volume and price data" },
        { text: "" },
        { text: "Analysis Pipeline:", bold: true },
        { text: "  1. News Collection: Automated ingestion from multiple financial news sources" },
        { text: "  2. Sentiment Analysis: LLM-powered analysis classifying market sentiment" },
        { text: "  3. Impact Mapping: AI assessment of news impact on specific assets" },
        { text: "  4. Risk Scoring: Multi-factor risk assessment combining sentiment confidence and impact magnitude" },
        { text: "" },
        { text: "Disclaimer: This report is for informational purposes only and does not constitute financial advice.", bold: true },
      ];
      methodLines.forEach((line) => {
        checkPage(5);
        if (line.text === "") { y += 3; return; }
        doc.setFont("helvetica", line.bold ? "bold" : "normal");
        doc.setFontSize(line.bold ? 8 : 7.5);
        doc.setTextColor(line.bold ? 30 : 71, line.bold ? 41 : 85, line.bold ? 59 : 105);
        const lines = doc.splitTextToSize(line.text, cw - 4);
        lines.forEach((l: string) => { doc.text(l, m + 2, y); y += 3.5; });
      });

      drawFooter(doc, pw, ph, pageNum);
      doc.save(`neural-engine-report-${new Date().toISOString().slice(0, 10)}.pdf`);
      showToast("PDF report downloaded", "success");
    } catch (err) {
      console.error("PDF generation failed:", err);
      showToast("Failed to generate PDF", "error");
    }
    setGenerating(false);
  };

  return (
    <button
      onClick={generate}
      disabled={generating}
      className="flex items-center gap-2 px-4 py-2 rounded-lg bg-gradient-to-r from-purple-500/20 to-rose-500/20 text-white text-sm font-medium border border-purple-500/30 hover:border-purple-500/60 transition-all disabled:opacity-50"
    >
      <Download className="h-4 w-4" />
      {generating ? "Generating..." : "Export PDF"}
    </button>
  );
}
